# These are supported funding model platforms

github: [zukahai, haizukon, haizuka2712]
liberapay: [zukahai]
issuehunt: [zukahai]
otechie: [zukahai]
custom: ["https://www.facebook.com/chiatayde/", "https://www.facebook.com/algorithmcpp", "https://www.facebook.com/NVNFONT"]
